### PR TITLE
Change project UI

### PR DESCRIPTION
**Pull request by aashish22bansal**
test

### CODE REVIEW

**Comment by tericcabrel** [comment]
Hello @aashish22bansal 👋🏾 
What are you trying to do?

**Comment by aashish22bansal** [comment]
> Hello @aashish22bansal 👋🏾 What are you trying to do?

Hi. I recently came across your website in which you provided the procedure to deploy a Spring Boot Application. I was trying to follow the same, however, I was not able to complete it. Did I affect the actual project?

**Comment by tericcabrel** [comment]
No, you didn't affect the actual project! What prevented you from completing the tutorial about deploying a Spring Boot application?

**Comment by aashish22bansal** [comment]
I think I made mistakes with the Docker setup and the configuring it with GitHub Actions.

**Pull request closed without merging**
